data = [
    {"name": "Cristiano Ronaldo", "follower_count": 625000000, "country": "Portugal", "profession": "Footballer"},
    {"name": "Lionel Messi", "follower_count": 505000000, "country": "Argentina", "profession": "Footballer"},
    {"name": "Selena Gomez", "follower_count": 430000000, "country": "USA", "profession": "Singer/Actress"},
    {"name": "Kylie Jenner", "follower_count": 400000000, "country": "USA", "profession": "Model/Businesswoman"},
    {"name": "Dwayne Johnson", "follower_count": 390000000, "country": "USA", "profession": "Actor/Wrestler"},
    {"name": "Ariana Grande", "follower_count": 380000000, "country": "USA", "profession": "Singer/Actress"},
    {"name": "Kim Kardashian", "follower_count": 370000000, "country": "USA", "profession": "Model/Businesswoman"},
    {"name": "Beyoncé", "follower_count": 360000000, "country": "USA", "profession": "Singer"},
    {"name": "Justin Bieber", "follower_count": 350000000, "country": "Canada", "profession": "Singer"},
    {"name": "Taylor Swift", "follower_count": 340000000, "country": "USA", "profession": "Singer"},
    {"name": "Virat Kohl", "follower_count": 320000000, "country": "India", "profession": "Cricketer"},
    {"name": "Jennifer Lopez", "follower_count": 310000000, "country": "USA", "profession": "Singer/Actress"},
    {"name": "Neymar Jr", "follower_count": 300000000, "country": "Brazil", "profession": "Footballer"},
    {"name": "Kendall Jenner", "follower_count": 290000000, "country": "USA", "profession": "Model"},
    {"name": "Nicki Minaj", "follower_count": 280000000, "country": "USA", "profession": "Rapper"},
    {"name": "Miley Cyrus", "follower_count": 270000000, "country": "USA", "profession": "Singer/Actress"},
    {"name": "Kourtney Kardashian", "follower_count": 260000000, "country": "USA", "profession": "Model/Businesswoman"},
    {"name": "Shakira", "follower_count": 250000000, "country": "Colombia", "profession": "Singer"},
    {"name": "Drake", "follower_count": 240000000, "country": "Canada", "profession": "Rapper"},
    {"name": "Billie Eilish", "follower_count": 230000000, "country": "USA", "profession": "Singer"},
    {"name": "Emma Watson", "follower_count": 220000000, "country": "UK", "profession": "Actress"},
    {"name": "Chris Hemsworth", "follower_count": 210000000, "country": "Australia", "profession": "Actor"},
    {"name": "Zac Efron", "follower_count": 200000000, "country": "USA", "profession": "Actor"},
    {"name": "Gal Gadot", "follower_count": 190000000, "country": "Israel", "profession": "Actress"},
    {"name": "Rihanna", "follower_count": 185000000, "country": "Barbados", "profession": "Singer/Entrepreneur"},
    {"name": "Zendaya", "follower_count": 180000000, "country": "USA", "profession": "Actress/Singer"},
    {"name": "Deepika Padukone", "follower_count": 175000000, "country": "India", "profession": "Actress"},
    {"name": "Shah Rukh Khan", "follower_count": 170000000, "country": "India", "profession": "Actor"},
    {"name": "Alia Bhatt", "follower_count": 165000000, "country": "India", "profession": "Actress"},
    {"name": "Ranveer Singh", "follower_count": 160000000, "country": "India", "profession": "Actor"},
    {"name": "Robert Downey Jr.", "follower_count": 155000000, "country": "USA", "profession": "Actor"},
    {"name": "Tom Holland", "follower_count": 150000000, "country": "UK", "profession": "Actor"},
    {"name": "Chris Evans", "follower_count": 145000000, "country": "USA", "profession": "Actor"},
    {"name": "Katrina Kaif", "follower_count": 140000000, "country": "India", "profession": "Actress"},
    {"name": "Priyanka Chopra", "follower_count": 135000000, "country": "India", "profession": "Actress"},
    {"name": "Salman Khan", "follower_count": 130000000, "country": "India", "profession": "Actor"},
    {"name": "Akshay Kumar", "follower_count": 125000000, "country": "India", "profession": "Actor"},
    {"name": "Hrithik Roshan", "follower_count": 120000000, "country": "India", "profession": "Actor"},
    {"name": "Anushka Sharma", "follower_count": 115000000, "country": "India", "profession": "Actress"},
    {"name": "Mahesh Babu", "follower_count": 110000000, "country": "India", "profession": "Actor"},
    {"name": "Allu Arjun", "follower_count": 105000000, "country": "India", "profession": "Actor"},
    {"name": "Ram Charan", "follower_count": 100000000, "country": "India", "profession": "Actor"},
    {"name": "Yash", "follower_count": 95000000, "country": "India", "profession": "Actor"},
    {"name": "Kajal Aggarwal", "follower_count": 90000000, "country": "India", "profession": "Actress"},
    {"name": "Rashmika Mandanna", "follower_count": 85000000, "country": "India", "profession": "Actress"},
    {"name": "Pooja Hegde", "follower_count": 80000000, "country": "India", "profession": "Actress"},
    {"name": "Disha Patani", "follower_count": 75000000, "country": "India", "profession": "Actress"},
    {"name": "Sunny Leone", "follower_count": 70000000, "country": "India", "profession": "Actress"},
    {"name": "Samantha Ruth Prabhu", "follower_count": 65000000, "country": "India", "profession": "Actress"},
]
